language: php
sudo: false

php:
  - 7.4

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.composer/cache
env:
  - DATABASE_URL=sqlite:///%kernel.project_dir%/var/app.db

before_install:
  - composer self-update

install:
  - composer install
  - touch var/app.db

  # Fixtures
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - php bin/phpunit
  - vendor/bin/phpstan analyse src tests --level=2

notification:
  email: false
