@startuml
class Consumer
class ConsumerAddresses

class Grower
class Hive
class Deliverer


class DeliveryAddress

Together {
class Order
class OrderLine {
    - productId
    - quantity
    - price
}
class Product
class Invoice {
    - number
    - filePath
    - invoiceLines
    - totalAmount
}

class InvoiceLine {
    - productDescription
    - quantity
    - price
}

}

Together {
class DeliveryAddress
class Deliverer
}

Consumer *-- ConsumerAddresses
Grower o-- Hive

Order *-- OrderLine

Hive o-- Product

OrderLine *-- Product

Consumer -- Order

Grower -- Order

Order *-- DeliveryAddress

Deliverer *-- DeliveryAddress




@enduml