App\Presentation\Api\Grower\Model\GrowerModel:
    collectionOperations:
      create_grower:
        method: POST
        path: /grower/create
        controller: App\Presentation\Api\Handler\RegisterGrowerHandler
        #security: is_granted('ROLE_GROWER')
