App\Presentation\Api\Consumer\Model\ConsumerModel:
  collectionOperations:
    create_consumer:
      method: POST
      path: /consumer/create
      controller: App\Presentation\Api\Handler\RegisterConsumerHandler

    #get_consumers:
    #  method: GET

App\Presentation\Api\Deliverer\Model\DelivererModel:
  collectionOperations:
    create_consumer:
      method: POST
      path: /deliverers
      controller: App\Presentation\Api\Handler\RegisterDelivererHandler

App\Presentation\Api\Grower\Model\GrowerModel:
  collectionOperations:
    create_grower:
      method: POST
      input: App\Application\UseCases\Grower\Register\RegisterGrowerRequest
      output: false
      path: /grower/create
      controller: App\Presentation\Api\Handler\RegisterGrowerHandler
      #security: is_granted('ROLE_GROWER')
  itemOperations:
    show_grower:
      method: GET
      path: /growers/{id}
      controller: App\Presentation\Api\Handler\ShowGrowerHandler
    update_grower:
      method: PUT
      input: App\Application\UseCases\Grower\AddProducts\AddProductsToHiveGrowerRequest
      output: false
      path: /growers/{id}
      controller: App\Presentation\Api\Handler\UpdateGrowerHandler



